export const Student = [
  {
    id: 1,
    first_name: "Meerim",
    last_name: "Malanova",
    email: "meerim.malakanova.kk@gmai.com",
    course: "PM",
  },
  {
    id: 2,
    first_name: "Sherbolot",
    last_name: "Arbaev",
    email: "arbaevsherbolot1@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 3,
    first_name: "Elkhan",
    last_name: "Sharshenbekov",
    email: "boss.armsport@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 4,
    first_name: "Zhamilya",
    last_name: "Aitkulieva",
    email: "zaytkulieva0317@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 5,
    first_name: "Jhusup",
    last_name: "Toktosunov",
    email: "jaj2232ajn@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 6,
    first_name: "Janetta",
    last_name: "Kattoeva",
    email: "jkattoeva@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 7,
    first_name: "Elniza",
    last_name: "Adylova",
    email: "elnizaadylkyzy63@gmail.com",
    course: "Full-Stack",
  },
  {
    id: 8,
    first_name: "Altynai",
    last_name: "Kyshtobaeva",
    email: "mskywtobaeva2@gmail.com",
    course: "UI-UX",
  },
  {
    id: 9,
    first_name: "Aizhamal",
    last_name: "Kuseinova",
    email: "kuseinovaaijamal@gmail.com",
    course: "SDET",
  },
  {
    id: 10,
    first_name: "Begimai",
    last_name: "Turusbekova ",
    email: "asankadyrova11@gmail.com",
    course: "SDET",
  },
  {
    id: 11,
    first_name: "Emir",
    last_name: "Kerimberdiev",
    email: "keremberdievemir43@gmail.com",
    course: "DevOPS",
  },
  {
    id: 12,
    first_name: "Madina",
    last_name: "Tad",
    email: "madina.tadjidinova@gmail.com",
    course: "DevOPS",
  },
  {
    id: 13,
    first_name: "Arlen",
    last_name: "Tursunbekov",
    email: "arlen.tursunbekov.2001@gmail.com",
    course: "DevOPS",
  },
];
